# type: ignore
"""task list metadata

Revision ID: 055369ad002b
Revises: d461ae4f5a1a
Create Date: 2025-03-21 08:49:28.711938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '055369ad002b'
down_revision: Union[str, None] = 'd461ae4f5a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_list', sa.Column('members_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('task_list', sa.Column('members_avatars', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.add_column('task_list', sa.Column('task_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('task_list', sa.Column('incomplete_tasks_count', sa.Integer(), server_default='0', nullable=False))
    op.create_unique_constraint(op.f('uq_user_progress_user_id'), 'user_progress', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_progress_user_id'), 'user_progress', type_='unique')
    op.drop_column('task_list', 'incomplete_tasks_count')
    op.drop_column('task_list', 'task_count')
    op.drop_column('task_list', 'members_avatars')
    op.drop_column('task_list', 'members_count')
    # ### end Alembic commands ###
