# type: ignore
"""create user

Revision ID: 1b65a065bd33
Revises: 
Create Date: 2024-12-11 16:07:56.208569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b65a065bd33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=False),
    sa.Column('avatar', sa.Uuid(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('soc_type', sa.String(), nullable=False),
    sa.Column('soc_token', sa.String(), nullable=False),
    sa.Column('firebase_device_token', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(length=128), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('user_contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['user.id'], name=op.f('fk_user_contacts_contact_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_contacts_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'contact_id', name=op.f('pk_user_contacts'))
    )
    op.create_table('user_settings',
    sa.Column('checkbox_style', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_settings_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('user_contacts')
    op.drop_table('user')
    # ### end Alembic commands ###
