# type: ignore
"""create banner

Revision ID: 2111d601becf
Revises: 2e3b333522cd
Create Date: 2025-02-09 06:45:02.129589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2111d601becf'
down_revision: Union[str, None] = '2e3b333522cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banner'))
    )
    op.create_table('languages',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_languages'))
    )
    op.create_table('banner_translations',
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sub_title', sa.String(), nullable=False),
    sa.Column('banner_id', sa.Integer(), nullable=False),
    sa.Column('languages_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banner_id'], ['banner.id'], name=op.f('fk_banner_translations_banner_id_banner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['languages_id'], ['languages.code'], name=op.f('fk_banner_translations_languages_id_languages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banner_translations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner_translations')
    op.drop_table('languages')
    op.drop_table('banner')
    # ### end Alembic commands ###
