# type: ignore
"""create user progress

Revision ID: 2e3b333522cd
Revises: d46b6b268a39
Create Date: 2025-01-31 19:53:58.276080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3b333522cd'
down_revision: Union[str, None] = 'd46b6b268a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_progress',
    sa.Column('total_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_progress_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_progress')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_progress_user_id'))
    )
    op.add_column('user', sa.Column('level', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level')
    op.drop_table('user_progress')
    # ### end Alembic commands ###
