# type: ignore
"""task has comment field

Revision ID: 373c0371144b
Revises: 055369ad002b
Create Date: 2025-03-22 02:35:07.285429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373c0371144b'
down_revision: Union[str, None] = '055369ad002b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('has_comment', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'has_comment')
    # ### end Alembic commands ###
