# type: ignore
"""add bg for icon category

Revision ID: 38b49499cb47
Revises: 711afa34137d
Create Date: 2025-01-15 17:49:08.221790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b49499cb47'
down_revision: Union[str, None] = '711afa34137d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icon_category', sa.Column('bg_image', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_task_list', 'task_list_invitation', type_='unique')
    # ### end Alembic commands ###
