# type: ignore
"""calendar member, invitation

Revision ID: 3d5e237a43ee
Revises: 2111d601becf
Create Date: 2025-02-16 15:10:14.955484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5e237a43ee'
down_revision: Union[str, None] = '2111d601becf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_invitation',
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('calendar_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_user_id'], ['user.id'], name=op.f('fk_calendar_invitation_calendar_user_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_calendar_invitation_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_invitation')),
    sa.UniqueConstraint('user_id', 'calendar_user_id', name='calendar_invitation_uq_user_calendar_user')
    )
    op.create_table('shared_calendar_member',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('calendar_user_id', sa.UUID(), nullable=False),
    sa.Column('shared_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_user_id'], ['user.id'], name=op.f('fk_shared_calendar_member_calendar_user_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_shared_calendar_member_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shared_calendar_member')),
    sa.UniqueConstraint('user_id', 'calendar_user_id', name='shared_calendar_member_uq_user_calendar_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_calendar_member')
    op.drop_table('calendar_invitation')
    # ### end Alembic commands ###
