#type: ignore
"""create task

Revision ID: 3e1235983f8b
Revises: ce703ee99979
Create Date: 2024-12-24 01:42:09.441220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1235983f8b'
down_revision: Union[str, None] = 'ce703ee99979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image', sa.Uuid(), nullable=True),
    sa.Column('task_list_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('target_datetime', sa.DateTime(), nullable=True),
    sa.Column('reminder', sa.String(), nullable=True),
    sa.Column('repeat', sa.String(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_task_owner_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_list_id'], ['task_list.id'], name=op.f('fk_task_task_list_id_task_list'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.create_table('task_comment',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_task_comment_author_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_comment_task_id_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_comment'))
    )
    op.create_table('task_performer',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_performer_task_id_task'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_task_performer_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'task_id', name=op.f('pk_task_performer'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_performer')
    op.drop_table('task_comment')
    op.drop_table('task')
    # ### end Alembic commands ###
