# type: ignore
"""reminder sent field

Revision ID: 41f75ec6e0cb
Revises: cd3ca1d0b676
Create Date: 2025-03-25 07:43:57.646233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f75ec6e0cb'
down_revision: Union[str, None] = 'cd3ca1d0b676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'reminder_sent')
    # ### end Alembic commands ###
