# type: ignore
"""create invitations

Revision ID: 57df6ec853ef
Revises: 5f15b64cca32
Create Date: 2024-12-27 02:19:32.447115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57df6ec853ef'
down_revision: Union[str, None] = '5f15b64cca32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_list_invitation',
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_list_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_list_id'], ['task_list.id'], name=op.f('fk_task_list_invitation_task_list_id_task_list'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_task_list_invitation_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_list_invitation')),
    sa.UniqueConstraint('user_id', 'task_list_id', name='uq_user_invitation_task_list')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_list_invitation')
    # ### end Alembic commands ###
