# type: ignore
"""create icons

Revision ID: 5d2e699abff4
Revises: c04c4aed306b
Create Date: 2024-12-12 20:49:16.568925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2e699abff4'
down_revision: Union[str, None] = 'c04c4aed306b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icon_category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icon_category'))
    )
    op.create_table('icon',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['icon_category.id'], name=op.f('fk_icon_category_id_icon_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icon'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icon')
    op.drop_table('icon_category')
    # ### end Alembic commands ###
