# type: ignore
"""add icon to group

Revision ID: 5f15b64cca32
Revises: 3966ba3542d2
Create Date: 2024-12-26 23:53:18.875837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f15b64cca32'
down_revision: Union[str, None] = '3966ba3542d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('icon_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_group_icon_id_icon'), 'group', 'icon', ['icon_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_group_icon_id_icon'), 'group', type_='foreignkey')
    op.drop_column('group', 'icon_id')
    # ### end Alembic commands ###
