# type: ignore
"""invite link

Revision ID: 6ba2ee42d1f1
Revises: f1378be7c843
Create Date: 2025-02-24 12:34:37.833894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba2ee42d1f1'
down_revision: Union[str, None] = 'f1378be7c843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_link',
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('task_list_id', sa.UUID(), nullable=True),
    sa.Column('inviter_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], name=op.f('fk_invite_link_inviter_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_list_id'], ['task_list.id'], name=op.f('fk_invite_link_task_list_id_task_list'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_link')),
    sa.UniqueConstraint('link', name=op.f('uq_invite_link_link'))
    )
    op.alter_column('leave_feedback', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_feedback', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('invite_link')
    # ### end Alembic commands ###
