# type: ignore
"""create avatar table

Revision ID: 711afa34137d
Revises: 57df6ec853ef
Create Date: 2025-01-02 07:45:25.306540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711afa34137d'
down_revision: Union[str, None] = '57df6ec853ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('image', sa.Uuid(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('lvl_required', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avatar'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avatar')
    # ### end Alembic commands ###
