# type: ignore
"""notification user settings

Revision ID: 8215b69aec52
Revises: 6ba2ee42d1f1
Create Date: 2025-02-28 20:48:53.296145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8215b69aec52'
down_revision: Union[str, None] = '6ba2ee42d1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('notification_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'notification_enabled')
    # ### end Alembic commands ###
