# type: ignore
"""removed task

Revision ID: 8ce2900e8a63
Revises: dc24b5fd16fa
Create Date: 2025-03-05 12:05:55.930330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce2900e8a63'
down_revision: Union[str, None] = 'dc24b5fd16fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('removed_task',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image', sa.Uuid(), nullable=True),
    sa.Column('task_list_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('full_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reminder', sa.String(), nullable=True),
    sa.Column('repeat', sa.String(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_used_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_list_id'], ['task_list.id'], name=op.f('fk_removed_task_task_list_id_task_list'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_removed_task'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('removed_task')
    # ### end Alembic commands ###
