# type: ignore
"""task category nullable

Revision ID: 90a6a826b044
Revises: d2b012403576
Create Date: 2025-05-22 20:29:32.200197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a6a826b044'
down_revision: Union[str, None] = 'd2b012403576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'task_list_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'task_list_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
