# type: ignore
"""user settings language

Revision ID: 9c244a6dca0c
Revises: d04728bf4c8f
Create Date: 2025-03-09 11:33:45.849855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c244a6dca0c'
down_revision: Union[str, None] = 'd04728bf4c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('language', sa.String(), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'language')
    # ### end Alembic commands ###
