# type: ignore
"""icon image add

Revision ID: 9fc2f6af8ae5
Revises: 6af80f60b3b9
Create Date: 2025-01-24 22:13:47.543758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc2f6af8ae5'
down_revision: Union[str, None] = '6af80f60b3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icon', sa.Column('image', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icon', 'image')
    # ### end Alembic commands ###
