# type: ignore
"""create task list

Revision ID: a1cb476d8a36
Revises: 5d2e699abff4
Create Date: 2024-12-12 20:50:51.038242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cb476d8a36'
down_revision: Union[str, None] = '5d2e699abff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_list',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('last_task_complete_date', sa.DateTime(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['icon_id'], ['icon.id'], name=op.f('fk_task_list_icon_id_icon'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_task_list_owner_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_list'))
    )
    op.create_table('task_list_member',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_list_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_list_id'], ['task_list.id'], name=op.f('fk_task_list_member_task_list_id_task_list'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_task_list_member_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_list_member')),
    sa.UniqueConstraint('user_id', 'task_list_id', name='uq_user_task_list')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_list_member')
    op.drop_table('task_list')
    # ### end Alembic commands ###
