# type: ignore
"""group meta field

Revision ID: cd3ca1d0b676
Revises: 373c0371144b
Create Date: 2025-03-22 03:11:57.588643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd3ca1d0b676'
down_revision: Union[str, None] = '373c0371144b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('members_avatars', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.add_column('group', sa.Column('members_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'members_count')
    op.drop_column('group', 'members_avatars')
    # ### end Alembic commands ###
