# type: ignore
"""task parent

Revision ID: d04728bf4c8f
Revises: dae246392d05
Create Date: 2025-03-08 07:03:49.719127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04728bf4c8f'
down_revision: Union[str, None] = 'dae246392d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_task_parent_id_task'), 'task', 'task', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_parent_id_task'), 'task', type_='foreignkey')
    op.drop_column('task', 'parent_id')
    # ### end Alembic commands ###
