# type: ignore
"""notification invitation rl

Revision ID: d2b012403576
Revises: 41f75ec6e0cb
Create Date: 2025-03-26 07:20:10.250623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b012403576'
down_revision: Union[str, None] = '41f75ec6e0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('calendar_invitation_id', sa.Integer(), nullable=True))
    op.add_column('notification', sa.Column('task_list_invitation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_notification_calendar_invitation_id_calendar_invitation'), 'notification', 'calendar_invitation', ['calendar_invitation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_notification_task_list_invitation_id_task_list_invitation'), 'notification', 'task_list_invitation', ['task_list_invitation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notification_task_list_invitation_id_task_list_invitation'), 'notification', type_='foreignkey')
    op.drop_constraint(op.f('fk_notification_calendar_invitation_id_calendar_invitation'), 'notification', type_='foreignkey')
    op.drop_column('notification', 'task_list_invitation_id')
    op.drop_column('notification', 'calendar_invitation_id')
    # ### end Alembic commands ###
