# type: ignore
"""remove unqiue cons

Revision ID: d461ae4f5a1a
Revises: 9c244a6dca0c
Create Date: 2025-03-09 15:31:40.540308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd461ae4f5a1a'
down_revision: Union[str, None] = '9c244a6dca0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calendar_invitation_uq_user_calendar_user', 'calendar_invitation', type_='unique')
    op.drop_constraint('uq_user_invitation_task_list', 'task_list_invitation', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_invitation_task_list', 'task_list_invitation', ['user_id', 'task_list_id'])
    op.create_unique_constraint('calendar_invitation_uq_user_calendar_user', 'calendar_invitation', ['user_id', 'calendar_user_id'])
    # ### end Alembic commands ###
