# type: ignore
"""notification sound

Revision ID: dae246392d05
Revises: 8ce2900e8a63
Create Date: 2025-03-08 06:36:30.447510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae246392d05'
down_revision: Union[str, None] = '8ce2900e8a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('notification_sound', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'notification_sound')
    # ### end Alembic commands ###
