# type: ignore
"""task private

Revision ID: dc24b5fd16fa
Revises: 8215b69aec52
Create Date: 2025-03-05 10:06:35.372860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc24b5fd16fa'
down_revision: Union[str, None] = '8215b69aec52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_private', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_private')
    # ### end Alembic commands ###
