# type: ignore
"""add icon lvl required field

Revision ID: e556ad40a30b
Revises: a1cb476d8a36
Create Date: 2024-12-12 21:21:58.432562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e556ad40a30b'
down_revision: Union[str, None] = 'a1cb476d8a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icon', sa.Column('lvl_required', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icon', 'lvl_required')
    # ### end Alembic commands ###
